# 该配置为反向连接示例
server:
  port: 12345

shiro:
  ws:
    server:
      enable: false
      url: "/ws/demo"
    client:
      enable: true
      url: "ws://127.0.0.1:3001"

  plugin-list:
    - com.esdllm.napcatbot.MenuPlugin
    - com.esdllm.napcatbot.SignPlugin
    - com.esdllm.napcatbot.BilibiliPushPlugin
    - com.esdllm.napcatbot.BilibiliAnalysisPlugin
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///napcatbot
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.esdllm.model
  global-config:
    db-config:
      logic-delete-field: isDelete  #全局逻辑删除
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      table-prefix:  # 设置表的前缀
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

myConfig:
  bot:
    qq:
    aiChat:
      token: ""
      base_url: "https://api.deepseek.com/chat/completions"
      max_tokens: 4096