server:
  port: 12345 #自行修改端口号

shiro:
  ws:
    server:
      enable: false
      url: "/ws/demo"
    client:
      enable: true
      url: "ws://127.0.0.1:3001"

  plugin-list:
    - com.esdllm.napcatbot.MenuPlugin
    - com.esdllm.napcatbot.SignPlugin
    - com.esdllm.napcatbot.BilibiliPushPlugin
    - com.esdllm.napcatbot.BilibiliAnalysisPlugin
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/napcatbot #数据库连接地址，本机为localhost，请自行修改数据库名
    username: root #数据库用户名，请自行修改
    password: root #数据库密码，请自行修改
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.esdllm.model
  global-config:
    db-config:
      logic-delete-field: isDelete  #全局逻辑删除
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      table-prefix:  # 设置表的前缀
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

myConfig:
  bot:
    qq: 123456789 # 改成你自己的机器人QQ号
    doubao:
      ARK_API_KEY: "your-ark-api-key" # 豆包的 ARK API KEY，请自行改成你的 ARK API KEY
      ARK_API_ID: "your-ark-api-id" # 豆包的 ARK API ID，请自行改成你的 ARK API ID